name: juju-db
base: core18
version: '3.6'
summary: Mongodb object/document oriented database used internally by Juju.
description: |
  Mongodb object/document oriented database used internally by Juju.
grade: devel
confinement: devmode

parts:
  wrappers:
    plugin: dump
    source: snap/local/

  mongo:
    plugin: dump
    source: https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.6.9.tgz
    source-type: tar
    prime:
      - bin/*
      - -bin/install_compass
      - -bin/bsondump
      - -bin/mongoexport
      - -bin/mongofiles
      - -bin/mongoimport
      - -bin/mongoperf
      - -bin/mongoreplay

apps:
  daemon:
    command: commands/daemon.start
    stop-timeout: 600s
    restart-condition: on-failure
    daemon: simple
    plugs:
      - network-bind

  mongod:
    command: mongod
    plugs:
      - network

  mongos:
    command: mongos
    plugs:
      - network

  mongo:
    command: mongo
    plugs:
      - network

  mongodump:
    command: mongodump
    plugs:
      - network

  mongorestore:
    command: mongorestore
    plugs:
      - network
  
  mongostat:
    command: mongostat
    plugs:
      - network

  mongotop:
    command: mongotop
    plugs:
      - network
