name: mongodb36
base: core18
version: '3.6'
summary: Mongodb object/document oriented database
description: |
  Mongodb object/document oriented database

grade: devel
confinement: devmode

parts:
  wrappers:
    plugin: dump
    source: snap/local/
    # organize:
    #   commands/: commands/

  mongo:
    plugin: dump
    source: https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.6.9.tgz
    source-type: tar
    prime:
      - bin/*
      - -bin/install_compass

# Add tools here too (incl. in tarball) or sep. snap?)
apps:
  mongod:
    command: mongod
    plugs:
      - network

  daemon:
    command: commands/daemon.start
    reload-command: commands/daemon.reload
    stop-command: commands/daemon.stop
    stop-timeout: 600s
    restart-condition: on-failure
    daemon: simple
    plugs:
      - network-bind

  mongos:
    command: mongos
    plugs:
      - network

  mongo:
    command: mongo
    plugs:
      - network

